### ISSUE TITLE
/usr/bin/aarch64-linux-gnu-ld: cannot find -lasound

### ISSUE THREAD

**Issue by adhirmndl** [mdrjr/c2_aml_libs#5]
/usr/bin/aarch64-linux-gnu-ld: cannot find -lasound
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'esplayer' failed
make[1]: *** [esplayer] Error 1
make[1]: Leaving directory '/home/odroid/ivis-codec/c2_aml_libs/example'
Makefile:4: recipe for target 'all' failed
make: [all] Error 2 (ignored)

-----------------------------------
odroid@odroid:~/hello_video_cx$ ls /usr/lib/aml_libs/
libadpcm.so  libamadec.so  libamavutils.so  libamcodec.so  libamr.so  libape.so  libcook.so  libfaad.so  libflac.so  liblibpcm_wfd.so  libmad.so  libpcm.so  libraac.so

libasound.so is missing 

please help

**Comment by mdrjr** [comment]
libasound is part of the Alsa.
You need to install alsa and its dev libs on w.e. distro you are using.
